# Generated by Django 6.0.4 on 2026-05-04 16:08

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Event = apps.get_model("event_app", "Event")
    Offer = apps.get_model("event_app", "Offer")
    from django.utils import timezone

    # Backfill created_at from event_start_date when available
    for ev in Event.objects.filter(created_at__isnull=True):
        ev.created_at = ev.event_start_date or timezone.now()
        ev.save(update_fields=["created_at"])

    # Create Offer rows for existing sale_url column if present
    # Some rows (from 0001) have sale_url on Event
    for ev in Event.objects.all():
        sale_url = getattr(ev, "sale_url", None)
        if sale_url:
            try:
                Offer.objects.create(event=ev, sale_url=sale_url, offer_type="migrated")
            except Exception:
                # ignore individual failures
                pass


def backwards(apps, schema_editor):
    Event = apps.get_model("event_app", "Event")
    Offer = apps.get_model("event_app", "Offer")
    # revert created_at to null for rows set by forwards
    for ev in Event.objects.all():
        ev.created_at = None
        ev.save(update_fields=["created_at"])
    # delete migrated offers
    Offer.objects.filter(offer_type="migrated").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("event_app", "0002_event_sale_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("sale_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="event_app.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name="event",
            name="sale_url",
        ),
    ]
