# Generated by Django 6.0.4 on 2026-05-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_app", "0005_alter_event_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="sale_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
