# Generated by Django 6.0.4 on 2026-05-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_alter_offer_sale_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='seat_map',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
